# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20160720_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='song_title',
            new_name='album_title',
        ),
    ]
