# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20160723_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.FileField(upload_to=''),
        ),
    ]
