# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20160728_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.AddField(
            model_name='song',
            name='title_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
