# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20161006_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='album',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, height_field='320', null=True, upload_to='', width_field='395'),
        ),
    ]
