# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20161006_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='height_field',
            field=models.IntegerField(default=395),
        ),
        migrations.AddField(
            model_name='album',
            name='width_field',
            field=models.IntegerField(default=320),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
    ]
