# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20161006_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 6, 14, 36, 57, 773208, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
